### ISSUE TITLE
Build Quality Checks: usage with pull requests from GitHub instead of Azure Repos

### ISSUE THREAD

**Issue by frankieyan** [MicrosoftPremier/VstsExtensions#102]
Hi there! I'm trying to set up Build Quality Checks with our project using Azure Pipelines + GitHub, but I'm a little lost when setting up the base branch to compare code coverage against.

For the two Build Service users, we only seem to see permissions around builds, ie. "Update build information", rather than git related permissions like "Contribute to pull requests". Is this due to not having Azure Repos? If so, is it possible for this to work with a project on Github?

Thanks in advance 😃

**Comment by frankieyan** [comment]
Attaching the configs just in case there's anything obvious missing:

```yaml
    - task: PublishCodeCoverageResults@1
      inputs:
          codeCoverageTool: 'cobertura'
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
      displayName: 'Publish code coverage result'

    - task: BuildQualityChecks@7
      inputs:
          checkWarnings: true
          checkCoverage: true
          coverageType: lines
          baseBranchRef: $(System.PullRequest.TargetBranch)
      displayName: 'Check build quality'
```
