### ISSUE TITLE
Coverage Policy Error Reported when createBuildIssues is false

### ISSUE THREAD

**Issue by pinkfloydx33** [MicrosoftPremier/VstsExtensions#113]
I have a coverage policy check where `createBuildIssues` is purposefully set to `false`. When the policy fails, an error is being emitted to the pipeline _as an error_ causing my pipeline to go 'yellow'. I run two different checks in the same pipeline, both fail but only the first emits the error. It seems that `createBuildIssues: false` is not working properly for `fixed` coverage checks.

This is the task that cause the error to be emitted:
```yaml
      - task: BuildQualityChecks@7
        displayName: 'Check Minimum Line Coverage'
        inputs:
          checkCoverage: true
          coverageFailOption: 'fixed'
          coverageType: lines
          treat0of0as100: true
          coverageThreshold: 70
          runTitle: 'Minimum Coverage'
          createBuildIssues: false
        continueOnError: true 
```

This check (also failing) does **not** emit an error onto the pipeline

```yaml
      - task: BuildQualityChecks@7
        displayName: 'Check Coverage Improvement'
        inputs:
          checkCoverage: true
          coverageFailOption: 'build'
          coverageType: 'lines'
          treat0of0as100: true
          forceCoverageImprovement: true
          coverageUpperThreshold: 70
          includePartiallySucceeded: false
          baseDefinitionId: '$(System.DefinitionId)'
          ignoreDecreaseAboveUpperThreshold: true    
          baseBranchRef: '$(PolicyCheck.TargetBranch)' # from another task
          runTitle: 'Required Improvement'
          createBuildIssues: 'false'
        continueOnError: true
```

We are running version `7.4.7` of the extension. Here is the full output of the log for the task that is not behaving properly:

```
SystemVssConnection exists true
Using IdentifierJobResolver
Validating code coverage policy...
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total lines: 335
Covered lines: 144
Code Coverage (%): 42.9851
##[error]At least one build quality policy was violated. See Build Quality Checks section for more details.
Finishing: Check Minimum Line Coverage
```

I've attached the full redacted log from running with `System.Debug=true`
[logs.txt](https://github.com/MicrosoftPremier/VstsExtensions/files/5104158/logs.txt)
