### ISSUE TITLE
Branch Coverage Uses Wrong Total Branches Value

### ISSUE THREAD

**Issue by ardalis** [MicrosoftPremier/VstsExtensions#120]
We have recently added the extension to our builds which have been using code coverage for quite some time. For one project we are getting this behavior:

![image](https://user-images.githubusercontent.com/782127/95890703-15d9b280-0d52-11eb-851a-5f14f448e1a7.png)

Total branches: 341
Covered branches: 106

However, looking at the code coverage tab for this same build, we see this:

![image](https://user-images.githubusercontent.com/782127/95890810-41f53380-0d52-11eb-8339-0057d4c0f191.png)

106 of 113 branches.

My initial thought was that the issue might be related to 0/0 branches, since the code coverage report shows quite a few of these. However, after updating our YAML as follows, the behavior remains unchanged:

```yaml
                - task: BuildQualityChecks@7
                  displayName: 'Check build branches quality'
                  inputs:
                    checkCoverage: true
                    coverageThreshold: 85
                    coverageType: branches
                    coverageFailOption: fixed
                    treat0of0as100: true
```

What else should we try?

**Comment by ReneSchumacher** [comment]
Hi Steve,

I assume you're using IstanbulJS to create the Cobertura report for code coverage, right? If so, this is a known bug in the cobertura report created by IstanbulJS. The Cobertura report contains a summary value for coverage as well es details for every class, function, and line of code. Azure DevOps, and thus BQC, only looks at the summary values, which have the correct value for coverage, while ReportGenerator ignores the summary values and looks at the details. Unfortunately, IstanbulJS does not correctly mark some of the branches in the Cobertura report, which leads to wrong numbrers.

I already fixed the issue in a PR months ago (see https://github.com/istanbuljs/istanbuljs/pull/518), but it still hasn't been accepted. I'm not even sure it will be accepted as the project is not very actively maintained anymore :( Nevertheless, I'll try my best to bring the maintainer to consider my PR.

**Comment by ardalis** [comment]
We're not using istanbuljs anywhere directly - does ReportGenerator use it?

Here's what we have (after running `dotnet test` to generate code coverage files):

```yaml
    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testRunner: 'VSTest'
        testResultsFiles: '**/*.trx'

    - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
      displayName: Test Code Coverage Report Generator
      inputs:
        reports: '$(Build.SourcesDirectory)/tests/{unittests}/coverage.cobertura.xml;$(Build.SourcesDirectory)/tests/{integrationtests}/coverage.cobertura.xml;$(Build.SourcesDirectory)/tests/{functionaltests}/coverage.cobertura.xml;'
        targetdir: '$(Build.SourcesDirectory)/CodeCoverage'
        reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
        assemblyfilters: '-xunit*'  

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
        reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
```
