### ISSUE TITLE
Version 7 no longer counts warnings (warningFilters)

### ISSUE THREAD

**Issue by Bouke** [MicrosoftPremier/VstsExtensions#125]
I'm running a linter (eslint) task as part of my build. This linter produces output like this:

```
X\app\components\catalog\category-node.ts(30,5): warning @typescript-eslint/explicit-module-boundary-types : Missing return type on function.
X\app\components\catalog\category-node.ts(60,13): warning @typescript-eslint/no-non-null-assertion : Forbidden non-null assertion.
X\app\components\catalog\category-node.ts(69,33): warning @typescript-eslint/no-non-null-assertion : Forbidden non-null assertion.
app/templates/product-catalog/category/products/create.hbs
  18:12  error  Do not use `action` as <button {{action ...}} />. Instead, use the `on` modifier and `fn` helper.  no-action
  20:12  error  Do not use `action` as <button {{action ...}} />. Instead, use the `on` modifier and `fn` helper.  no-action
```

I want to verify the lint issue count against the baseline, to ensure no new issues are introduced. The count is determined by counting the occurrences of the words "error" or "warning". This used to work fine with version 6, but version 7 is reporting 0 issues.

```yaml
#version 6:
    - task: BuildQualityChecks@6
      inputs:
        checkWarnings: true
        warningFailOption: 'build'
        showStatistics: true
        warningTaskFilters: '/^Lint/'
        warningFilters: '/(warning|error)/'
        baseDefinitionId: '25'
        baseRepoId: 'ef191fe7-612d-4dbc-9b0a-defb197d4ec6'
        baseBranchRef: '$(System.PullRequest.TargetBranch)'

#version 7:
    - task: BuildQualityChecks@7
      inputs:
        checkWarnings: true
        warningFailOption: 'build'
        showStatistics: true
        warningTaskFilters: '/^Lint/'
        warningFilters: '/(warning|error)/'
        baseDefinitionId: '25'
        baseRepoId: 'ef191fe7-612d-4dbc-9b0a-defb197d4ec6'
        baseBranchRef: '$(System.PullRequest.TargetBranch)'
```

This is the output from both tasks:

```
Version      : 6.4.4
(...)
Running task warnings analysis...
Counting warnings from tasks:
  - Lint X
Waiting for log information of task 'Lint X'...
     Running generic task log analysis...
     Total warnings: 538, Filtered warnings: 538
Overall total warnings: 538
Overall filtered warnings: 538
Found baseline build with ID 15602.
Running task warnings analysis...
Counting warnings from tasks:
  - Lint X
     Running generic task log analysis...
     Total warnings: 526, Filtered warnings: 526
[SUCCESS] Warnings policy passed with 538 warning(s).
Finishing: Check lint issue count
```

```
Version      : 7.6.2
(...)
Running task warnings analysis...
Counting warnings from tasks:
  - Lint X
     Running generic task log analysis...
     Total warnings: 0, Filtered warnings: 0
Overall total warnings: 0
Overall filtered warnings: 0
Found baseline build with ID 15601.
Running task warnings analysis...
Counting warnings from tasks:
  - Lint X
     Running generic task log analysis...
     Total warnings: 0, Filtered warnings: 0
Overall total warnings: 0
Overall filtered warnings: 0
[SUCCESS] Warnings policy passed with 0 warning(s).
Statistics generation took 64.144ms
Finishing: Check lint issue count
```

Any help would be appreciated.
