### ISSUE TITLE
BQC count warnings in version 7/8?

### ISSUE THREAD

**Issue by Bouke** [MicrosoftPremier/VstsExtensions#129]
This is somewhat related to #125, but now I'm trying to use the following documented use-case:

> Warning Filters (Tasks) can also be used to count warnings if a build task does not log warnings as build issues, as long as the task logs the number of warnings to its log file. To do so, specify a warning filter that contains exactly one unnamed capture group that matches the number of warnings. The captured number will be added to the total warning count as well was the filtered warning count.

I'm building using `dotnet build` and I want to compare the build error count. Whether the build fails or not is not relevant, however I want to reduce the overall build errors.

The output from `dotnet build` is the following:
```
(...)
    108 Warning(s)
    60 Error(s)
```

So my task looks like this:
```
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: 'build'
        arguments: '--framework net5.0 --configuration $(buildConfiguration)'
        workingDirectory: Source/
      continueOnError: true
    - task: BuildQualityChecks@8
      displayName: 'Check build errors'
      inputs:
        checkWarnings: true
        warningFailOption: 'build'
        showStatistics: true
        warningTaskFilters: '/^dotnet build$/'
        warningFilters: '/(\d+) Error\(s\)/'
        baseDefinitionId: '25'
        baseRepoId: 'ef191fe7-612d-4dbc-9b0a-defb197d4ec6'
        baseBranchRef: '$(System.PullRequest.TargetBranch)'
        runTitle: 'Check Build Errors'
```

On v8 this gives the following incorrect result:
```
     Total warnings: 110, Filtered warnings: 0
[SUCCESS] Warnings policy passed with 0 filtered warning(s) out of 110 total warning(s).
```

On v6 this produces the expected outcome:
```
     Total warnings: 170, Filtered warnings: 60
[ERROR] The number of filtered warnings (60 out of 170) has increased since the previous build! The previous build had 0 filtered warning(s) out of 0 total warning(s).
```

How to achieve the behaviour of v6 in v8?
