### ISSUE TITLE
Triggered by a pull request. Skip linking pull request

### ISSUE THREAD

**Issue by infratidev** [MicrosoftPremier/VstsExtensions#168]
Hi,

Thanks guys for developing this extension.
I have the following scenario:

**branches:**

- feature
- dev

When I do a PR of the feature to dev, I do the approval and the merge, pipeline is triggered in dev. When the build breaks, the workitem is created normally, but the build does not link with the PR.

The task's return message shows:

```
Successfully created new work item with ID 14242.
Successfully linked work item with ID 14242 to work item(s) 14234
Current build has not been triggered by a pull request. Skip linking pull request.
Finishing: Create work item on failure
```
Apparently the task has the correct parameters, below:

```
    - task: CreateWorkItem@1
      displayName: 'Create work item on failure' 
      inputs:
        teamProject: '$(System.TeamProject)'
        workItemType: 'Issue'
        title: '$(System.TeamProject) - Build $(Build.BuildNumber) Failed'
        assignedTo: '$(Build.RequestedFor) <$(Build.RequestedForEmail)>'
        fieldMappings: 'Branch $(Build.SourceBranch) failed to build. Go to Boards>WorkItems and tag the failure type.'
        associate: true
        linkWorkItems: true
        linkType: 'System.LinkTypes.Hierarchy-Forward'
        linkTarget: 'associate'
        linkPR: true
        preventDuplicates: true
        keyFields: |
          System.Title
          System.State
        updateDuplicates: true
        updateRules: 'Tags|=;Build $(Build.BuildNumber)'
      condition: failed()
```

Is it a problem?
