### ISSUE TITLE
BuildQualityChecks@8 - warningTaskFilters regex validation

### ISSUE THREAD

**Issue by ben-002** [MicrosoftPremier/VstsExtensions#177]
**Describe the context**
- **Extension:** *BuildQualityChecks*
- **Environment:** *Azure DevOps Services (cloud)*
- **Agent type:** *Microsoft-hosted*
- **Pipeline type:** *yaml *

warningTaskFilters: '^(Build.*)$'

For BuildQualityChecks@8 returns: The expression '^(Build.*)$' is not a valid regular expression and will be ignored.
Suceeds with BuildQualityChecks@6.

Also, I validated the regex with https://regex101.com/ and is a valid one

**Comment by ReneSchumacher** [comment]
Hi @ben-002,

thanks for reporting this. I cannot remember that we changed anything with regards to the warning task filters, but I'll check and will fix as soon as possible.

René

**Comment by ReneSchumacher** [comment]
Hi again,

are you really providing the regular expression as shown in your comment? That should have always failed as there aren't any delimiters for the regex. The proper syntax would be something like `/^(Build.*)$/`.

We did slightly change the code to parse the regular expression for better regex option handling. This is why it is now failing because of the missing delimiters. In v6 of the task, your expression was used but it was altered due to the missing delimiters. The resulting expression was `(Build.*)$` without the initial `^` character.

Could you please add the delimiters to your expression?

**Comment by ncook-hxgn** [comment]
.. could I get a bit of related guidance?

I'm trying to capture the displayName "CppCheck Scan" - this regex (`'/^(CppCheck\\sScan)$/i'`) should do it, right?
I validated the regex at the same site, regex101.com
![image](https://user-images.githubusercontent.com/36889813/207937714-9288ac4d-85ca-4374-ac50-35e01b5743dc.png)

But I get the following:
```bat
[WARNING] The specified task filters did not match any build task.
##[warning]The specified task filters did not match any build task.
```


The yaml for the BQC plugin looks like this:
```yaml
- task: CmdLine@2
  displayName: "CppCheck Scan"
  inputs:
    script: |
      cppcheck $(CodeOmittedForBerevity)
    workingDirectory: '$(Build.SourcesDirectory)'

- task: BuildQualityChecks@8
  displayName: 'CppCheck Gate'
  inputs:
    # ===== Warnings Policy Inputs =====
    checkWarnings: true
    warningFailOption: build
    showStatistics: true
    evaluateTaskWarnings: true
    warningTaskFilters: '/^(CppCheck\\sScan)$/i'
```
