### ISSUE TITLE
Warning Filters do not seem to screen out specified build warnings

### ISSUE THREAD

**Issue by ajurry** [MicrosoftPremier/VstsExtensions#185]
**Describe the context**
- **Extension:** BuildQualityChecks
- **Environment:** Azure DevOps Services (cloud)
- **Agent type:** Self-Hosted Agent
  - **Agent version:** Standard_B12ms
- **Pipeline type:** YAML Pipeline

**Describe the problem and expected behavior**
I'm currently trying to setup the BuildQualityChecks on my current build pipeline, to ignore two specific warnings, but it doesn't seem to work. 

My current task is setup like the following, with the bonus entries for debugging issues.
```
      - task: BuildQualityChecks@8
        displayName: 'Task: Check no build warnings introduced'
        inputs:
          checkWarnings: true
          warningFailOption: 'fixed'
          warningThreshold: 0
          showStatistics: true
          warningFilters: |
            /^.+\[warning\].+(MSB3277).+/i
            /^.+\[warning\].+(MSB3247).+/i
          fallbackOnPRTargetBranch: true
```

The build job has the following warnings present
```
2022-06-12T22:03:54.3486440Z ##[warning]e_config Tests\config_json_test.cpp(23,0): Warning XUNIT1: config_json_test::test_reads - 1 == 0
##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): Warning MSB3277: ...
##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): Warning MSB3247: ...
```

The basic output for BuildQualityChecks
```
Overall total warnings: 3
Overall filtered warnings: 0
[SUCCESS] Warnings policy passed with 0 filtered warning(s) out of 3 total warning(s).
No baseline build for current branch found. Looking for builds on pull request target branch.
```

In which it has found the three warnings, but seems to say that it succeeded, even though one of the warnings should cause this task to fail. Note, I have added a dummy warning by creating a test that should fail.

**Other notes**
- If I remove the warningFilters entirely, it fails, saying their are three issue found (expected behaviour)
- If I remove one of the entries, like `MSB3277`, it passes even though it should definately fail, but succeeds
- I also added some other patterns, all of which seem to lead to a build success.
If I remove the warningFilters entirely, it fails, saying that their are three issues found. I have also found that any input inside the 

As a work around, I am planning to just set the warning limit to a specific number of warnings for the time being, which should cause the above task to fail.

If the above is just a small issue on my part, feel free to reply with a possible resolution and I give it a go!
