### ISSUE TITLE
Yaml task not found

### ISSUE THREAD

**Issue by JeffreyGarrett** [MicrosoftPremier/VstsExtensions#20]
When trying to operate as a yaml file task is not recognized by azure build. 

Error: Job Job1: Step references task 'BuildQualityChecks' at version '5' which does not exist.

- task: BuildQualityChecks@5
  displayName: 'Check build quality'
  inputs:
    checkWarnings: true
   forceFewerWarnings: true
    showStatistics: true
    checkCoverage: true
    coverageDeltaType: percentage
    buildConfiguration: 25
    includePartiallySucceeded: false

Please let me know if I'm doing something incorrect or if this is not quite supported.  I got the yaml from the design editor so figured it should work.

**Comment by ReneSchumacher** [comment]
Hi Jeffrey,

our task also works in yaml builds (I just retested again). However, your yaml looks a bit strange. The task name should have a namespace syntax and the inputs look as if some things are missing and some are wrong. When I generate the yaml for the task using your configuration (or what I assume would be your configuration), I end up with this:

```
- task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@5
  displayName: 'Check build quality'
  inputs:
    checkWarnings: true
    forceFewerWarnings: true
    showStatistics: true
    checkCoverage: true
    coverageFailOption: fixed
    coverageThreshold: 25
```

You could try to copy this to your yaml file. Let me know if it helps or if you need anything else.

Happy building,
René
