### ISSUE TITLE
failed a CI is there are any warning 

### ISSUE THREAD

**Issue by smarteez17** [MicrosoftPremier/VstsExtensions#200]
Hi, there I have been tasked to fail any CI pipeline if there are any warnings. I using this code and only getting "Waiting for code coverage data ... " ( i am not sure if the steps are correct too ) . Please help 

In my code there 180 warning after I build the api 

  - task: BuildQualityChecks@8 
        displayName: 'Check Solution For Warning' 
        inputs:

            checkCoverage: true
            coverageFailOption: fixed
            coverageThreshold: 0

**Comment by ReneSchumacher** [comment]
Hi @smarteez17,

the simplest way to reach your goal is to treat warnings as errors. The compiler should have an option for this (e.g., see https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings). Your pipeline will then always fail if there are any warnings.

If you want to fail only when a certain number of warnings is exceeded or when the number of warnings increased, you can use the BuildQualityChecks task like this:

**Fixed threshold:**
```yaml
- task: BuildQualityChecks@8
  displayName: 'Check warnings'
  inputs:
    checkWarnings: true
    warningFailOption: fixed
    warningThreshold: <your threshold>
```

**Increasing number of warnings:**
```yaml
- task: BuildQualityChecks@8
  displayName: 'Check warnings'
  inputs:
    checkWarnings: true
```

Hope that helps.
