### ISSUE TITLE
Build Quality Checks - add option to ignore absence of coverage data

### ISSUE THREAD

**Issue by melezhik** [MicrosoftPremier/VstsExtensions#207]
Right now in case of absence of code coverage data, the plugins times out and prints out:

```
Waiting for code coverage data...
```

I would like to have an option to not to wait for a coverage data **and mark entire task status as success** in case of no coverage data presents: ( something like `dont_wait_for_data` or whatever you like to name it)

```yaml
    - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@8
      displayName: 'Check build quality'
      inputs:
        checkCoverage: true
        coverageFailOption: fixed
        coverageType: lines
        coverageThreshold: 50
        dont_wait_for_data: true
```  

This would be helpful in case developers for some reasons have not yet implemented test coverage in their unit tests but we still want to run those tests and don't hang on this step. Once test coverage is implemented by a developer this plugin should work as normal ...
