### ISSUE TITLE
BuildQualityChecks sums up coverage data of multiple runs when rerun a build

### ISSUE THREAD

**Issue by mabihz** [MicrosoftPremier/VstsExtensions#232]
**Describe the context**
- **Extension:** BuildQualityChecks
- **Pipeline type:** yaml pipeline

When a build is started once again (rerun), BQC seems to call in coverage data from all runs and sums up the values (in my case total blocks and covered blocks).
This is a problem if the first run failed with a low code coverage (caused by any reason) and the second one should succeed because of a good coverage, but both runs get sumed up and the average is not high enough.

I proofed that, by running a successfull build two times. In the second run, the code coverage percentage was the same, but the blocks were the double of the first run.

If I would know, where the coverage data is called from, maybe I could handle that by cleaning it up.
In the end BQC should not sum up coverage data of multiple runs.

**Comment by mabihz** [comment]
What i have already tried and did not help:
* Cleanup the TestResults directory
* Overwrite Code Coverage Reports artifact (as "latest.coverage")
* not produce any Code Coverage Reports artifact

**Comment by ReneSchumacher** [comment]
Hi  @mabihz,

sorry for the late response, I somehow missed this issue. Can you tell me what type of code coverage you are using and how you're publishing coverage? I would like to repro the issue on our side.

There is a built-in coverage aggregation in Azure DevOps, which might lead to this issue if you automatically rerun a job within a pipeline. Once the pipeline has finished and you then manually rerun the job, coverage data shouldn't be aggregated anymore. But I'll have to check this on the Azure DevOps side. BQC simply reads the data from Azure DevOps. Thus, if Azure DevOps aggregates data, there is no way for BQC to know that.

**Comment by mabihz** [comment]
Hi Rene,

nice to conversate with a countryman, but i keep writing in english for community.
In my case the code coverage comes from VsTest as .coverage files. 
The test results get published via PublishBuildArtifacts task. I also tried, without that publish step, but the problem remained.

Here are the 3 relevant steps from the pipeline:

```yaml
  - task: VSTest@1
    displayName: 'Test ausführen'
    inputs:
      testAssembly: '**\$(BuildConfiguration)\*test*.dll;-:**\obj\**'
      testFiltercriteria: 'testCategory!=Integration'
      runSettingsFile: ${{parameters.componentSlnPath}}\${{parameters.componentRunSettingsFile}}
      codeCoverageEnabled: true
      runInParallel: False
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      
  - task: PublishBuildArtifacts@1
    displayName: 'CodeCoverage Report'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)\TestResults'
      ArtifactName: TestResults

  - task: BuildQualityChecks@8
    displayName: 'Check Code Coverage'
    inputs:
      checkCoverage: true
      coverageFailOption: 'build'
      coverageType: 'blocks'
      allowCoverageVariance: true
      coverageVariance: '0.1'
      buildConfiguration: '$(BuildConfiguration)'
      buildPlatform: '$(BuildPlatform)'
      includePartiallySucceeded: false
      baseDefinitionId: '$(Build.DefinitionName)'
      baseRepoId: '$(Build.Repository.Name)'
      baseBranchRef: '$(System.PullRequest.TargetBranch)'
```
