### ISSUE TITLE
Code coverage check is not failing the build

### ISSUE THREAD

**Issue by IvanAlekseev** [MicrosoftPremier/VstsExtensions#47]
Hello, this extension worked perfectly for me for some time, but now it doesn't fail the build when coverage goes down. Can you point me at what am I doing wrong here?

Here is a build task:
```yml
      - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
        displayName: 'Check code coverage'
        inputs:
          checkWarnings: false
          checkCoverage: true
          coverageFailOption: build
          coverageType: branches
          baseBranchRef: refs/heads/master
```

It produces this log:
```
Starting: Check code coverage
==============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 6.1.2
Author       : Microsoft Premier Services
Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Validating code coverage policy...
Successfully read code coverage data from build.
Total branches: 3181
Covered branches: 1595
Code Coverage (%): 50.1415
Found baseline build with ID 120641.
Successfully read code coverage data from build.
Total branches: 3132
Covered branches: 1614
Code Coverage (%): 51.5326
Finishing: Check code coverage
```

According to the log it should fail, but it doesn't.
