### ISSUE TITLE
Regression in 6.2.2 and 6.2.1 of Build Quality Checks?

### ISSUE THREAD

**Issue by andrebriggs** [MicrosoftPremier/VstsExtensions#64]
Possibly related to #57 FYI, I'm using GitHub to host the code repositories. 

## My config
<pre>
  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
    displayName: 'Check build quality'
    inputs:
      checkWarnings: false
      warningFailOption: fixed
      warningFilters: ''
      showStatistics: true
      checkCoverage: true
      <b>coverageFailOption: 'Previous Value'</b>
      coverageType: branches
      buildConfiguration: ''
      buildPlatform: ''
      explicitFilter: true
      baseDefinitionId: 128
      <b>baseBranchRef: refs/heads/master</b>
      runTitle: 'Code Coverage Evaluation'
    condition: and(eq(variables['Agent.JobStatus'], 'Succeeded'), endsWith(variables['Agent.JobName'], 'node_12_x'))
</pre>

## Version 6.1.2
```
Starting: Check build quality
==============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 6.1.2
Author       : Microsoft Premier Services
Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Validating code coverage policy...
Successfully read code coverage data from build.
Total branches: 1133
Covered branches: 681
Code Coverage (%): 60.1059
Found baseline build with ID 9446.
Successfully read code coverage data from build.
Total branches: 1133
Covered branches: 681
Code Coverage (%): 60.1059
Finishing: Check build quality
```
## Version 6.2.1
```
Starting: Check build quality
==============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 6.2.1
Author       : Microsoft Premier Services
Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Using IdentifierJobResolver
Validating code coverage policy...
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total branches: 1133
Covered branches: 681
Code Coverage (%): 60.1059
Cannot read property 'evaluate' of undefined
[ERROR] Cannot read property 'evaluate' of undefined
##[error]Cannot read property 'evaluate' of undefined
##[error]At least one build quality policy was violated. See Build Quality Checks section for more details.
Finishing: Check build quality
```
## Version 6.2.2
```
Starting: Check build quality
==============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 6.2.2
Author       : Microsoft Premier Services
Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Using IdentifierJobResolver
Validating code coverage policy...
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total branches: 1133
Covered branches: 681
Code Coverage (%): 60.1059
Cannot read property 'evaluate' of undefined
[ERROR] Cannot read property 'evaluate' of undefined
##[error]Cannot read property 'evaluate' of undefined
##[error]At least one build quality policy was violated. See Build Quality Checks section for more details.
Finishing: Check build quality
```

**Comment by ReneSchumacher** [comment]
Hi @andrebriggs,

the YAML configuration is invalid. The coverageFailOption can either be _build_ or _fixed_ but not _Previous Value_ (see https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/WarningsPolicy.md#failoption). I would have thought that the build system would throw an error when you specify an invalid entry in YAML as this clearly violates the allowed options in the task.json. Apparently, it doesn't. We'll add error handling for this in the next update.

To fix the issue, please set the coverageFailOption to **build**.

**Comment by andrebriggs** [comment]
@ReneSchumacher thanks. Changing the `coverageFailOption` to build made the error go away. I now see references to code coverage that aren't  quite what I expected. Perhaps you can help me understand.


I have a log from a build [here](https://dev.azure.com/abrig/spk/_build/results?buildId=1146&view=logs&j=f164dbd1-368a-58ba-3795-906e0bb83435&t=ab609c07-f227-54ac-3087-e06c1b252f71) :
```
Starting: Check build quality
==============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 6.2.2
Author       : Microsoft Premier Services
Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Using IdentifierJobResolver
Validating code coverage policy...
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total branches: 1157
Covered branches: 693
Code Coverage (%): 59.8963
Found baseline build with ID 1144.
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total branches: 1133
Covered branches: 681
Code Coverage (%): 60.1059
[SUCCESS] Code coverage policy passed with 59.8963% (693 branches).
Finishing: Check build quality
```

The code coverage referred to above is  __59.8963__ and from build __1144__ (see coverage report here: https://dev.azure.com/abrig/spk/_build/results?buildId=1144&view=codecoverage-tab)

I'm assuming the __59.8963__ value refers to the circled value in the screenshot below (Not rounded up if so)?
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/3119513/72305642-45278b80-3629-11ea-8721-8f4c62f4800b.png">

If so why that particular value? The overall branch coverage isn't close to that value at all. Moreover the 2nd code coverage value in the build log of __60.1059__ doesn't see to correspond with anything in the build from the log (build 1146 [here](https://dev.azure.com/abrig/spk/_build/results?buildId=1146&view=codecoverage-tab))

I'm probably misunderstanding the instructions but the line `[SUCCESS] Code coverage policy passed with 59.8963% (693 branches).` from the build log makes it seem like __59.8963__ is the current coverage number where it is in fact less than the __60.1059__ the log refers to.

My configuration is here: 
```
  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
    displayName: 'Check build quality'
    inputs:
      checkWarnings: false
      warningFailOption: fixed
      warningFilters: ''
      showStatistics: true
      checkCoverage: true
      coverageFailOption: build
      coverageType: branches
      buildConfiguration: ''
      buildPlatform: ''
      explicitFilter: true
      baseDefinitionId: $(SPK_DEFINITION_ID) # Is 20 from https://dev.azure.com/abrig/spk/_build?definitionId=20&_a=summary
      baseBranchRef: refs/heads/master
      runTitle: 'Code Coverage Evaluation'
    condition: and(eq(variables['Agent.JobStatus'], 'Succeeded'), endsWith(variables['Agent.JobName'], 'node_12_x'))
```

**Comment by andrebriggs** [comment]
Another thing @ReneSchumacher. After looking at the documentation again I decided to remove `buildConfiguration`, `buildPlatform`, and  `explicitFilter`:
```
  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
    displayName: 'Check build quality'
    inputs:
      checkWarnings: false
      warningFailOption: fixed
      warningFilters: ''
      showStatistics: true
      checkCoverage: true
      coverageFailOption: build
      coverageType: branches
      # buildConfiguration: ''
      # buildPlatform: ''
      # explicitFilter: true
      baseDefinitionId: $(SPK_DEFINITION_ID)
      baseBranchRef: refs/heads/master
      runTitle: 'Code Coverage Evaluation'
    condition: and(eq(variables['Agent.JobStatus'], 'Succeeded'), endsWith(variables['Agent.JobName'], 'node_12_x'))
```

After that I get the same value (__59.8963__) for coverage in the comparison. I expect the same value since no code was changed but still confused about where the value is coming
```
==============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 6.2.2
Author       : Microsoft Premier Services
Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Using IdentifierJobResolver
Validating code coverage policy...
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total branches: 1157
Covered branches: 693
Code Coverage (%): 59.8963
Found baseline build with ID 1146.
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total branches: 1157
Covered branches: 693
Code Coverage (%): 59.8963
[SUCCESS] Code coverage policy passed with 59.8963% (693 branches).
Finishing: Check build quality
```

**Comment by andrebriggs** [comment]
@ReneSchumacher  Looks like the __59.8963__ value is the `branch-rate` from the `cobertura-coverage.xml` file. Correct?

```xml
<coverage lines-valid="2368" lines-covered="1701" line-rate="0.7182999999999999" branches-valid="1157" branches-covered="693" branch-rate="0.599" timestamp="1578966048486" complexity="0" version="0.1">
```

This must be an issue with the code coverage HTML generation not matching what is in the `cobertura-coverage.xml` file. Sorry for the confusion

**Comment by ReneSchumacher** [comment]
Hi @andrebriggs,

as you already figured out the coverage value is taken from the cobertura coverage file. Or more precisely: our task just queries coverage for a build using the Azure DevOps REST API and Azure DevOps simply takes the coverage data from the coverage result file (in your case cobertura). Unfortunately, the testing tools team decided to use the OSS tool ReportGenerator (see https://github.com/danielpalme/ReportGenerator) to render the code coverage report in the Azure DevOps UI. This tool, however, parses the coverage file and does not use the summary information. While parsing, they get different coverage values.

We already talked to the ReportGenerator team and they are convinced that their strategy is correct. The testing tools team apparently isn't very keen on fixing this issue, and I am trying to figure out how to fix it without having to run code coverage analysis myself. Since cobertura is (afaik) just the format, I guess the issue is in the Istanbul coverage generator. Are you using Istanbul to generate code coverage?

The buildPlatform, buildConfiguration, and explicitFilter parameters don't make any difference in your case, because you are generating coverage data that is not assigned with a specific configuration or platform. Imho, only our VSTest runner adds that information to the coverage data so that you can distinguish between coverage for multiple configurations in a multi-config build.

René

**Comment by ReneSchumacher** [comment]
Hi @andrebriggs,

I just published v6.2.3 of the task that fixes the exception you mentioned. The task will still fail with a proper error message when the YAML properties are invalid. I'm still trying to figure out why the values differ between ReportGenerator and Cobertura/Istanbul. However, since we cannot fix this behavior in our task, I'm closing the issue but keep digging.

René

**Comment by ReneSchumacher** [comment]
@andrebriggs: I did a couple evaluations of several Cobertura reports and the corresponding ReportGenerator output and finally found the reason for the different coverage values. Apparently Istanbul does not properly report switch statements in the Cobertura report. Thus, ReportGenerator does not notice branches that are created through switch statement. I have reported this in the ReportGenerator project (see https://github.com/danielpalme/ReportGenerator/issues/289) and will also create an issue in the Istanbul project in hopes that someone will fix it.

**Comment by danielpalme** [comment]
> Unfortunately, the testing tools team decided to use the OSS tool ReportGenerator (see https://github.com/danielpalme/ReportGenerator) to render the code coverage report in the Azure DevOps UI.

The problem is, that the report generated by Instanbul is not consistent. If [ReportGenerator](https://github.com/danielpalme/ReportGenerator) would use the summary value (0.8889), then the branches in the code (6 of 6) wouldn't match that result.  
So you can't blame ReportGenerator for that!

**Comment by ReneSchumacher** [comment]
Hey @danielpalme,

I'm not _blaming_ anyone and I have explained the issue here and in the issue I created in your repo. It is still _unfortunate_ that we decided to use ReportGenerator in this case, since our build summary showed the (correct) value from the coverage summary before. Since we switched to ReportGenerator, the coverage value shown in the code coverage section is wrong due to the incorrect data in the Cobertura file.

As I said, I'm going to open an issue with the Istanbul team so we can hopefully fix this. Istanbul apparently has the correct values, since the summary values are all correct. However, someone forgot to put switches and jumps into the report details. The good news is, though, that the data reported by our task is correct :D

So don't worry, ReportGenerator is still a great tool and it wasn't my intention to do you or the tool any harm.

René

**Comment by ReneSchumacher** [comment]
Just for reference: https://github.com/istanbuljs/istanbuljs/issues/517

**Comment by andrebriggs** [comment]
Thanks for the follow up @ReneSchumacher. I might have to look into the Istanbul code.

One more question. The log below has the Build Quality Checks passing when the current code coverage is  **59.8963** and the previous (baseline) code coverage is **60.1059**. I would have expected the task to fail? Perhaps the configuration is incorrect again? 

```
Starting: Check build quality
==============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 6.2.4
Author       : Microsoft Premier Services
Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Using IdentifierJobResolver
Validating code coverage policy...
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total branches: 1157
Covered branches: 693
Code Coverage (%): 59.8963
Found baseline build with ID 9446.
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total branches: 1133
Covered branches: 681
Code Coverage (%): 60.1059
[SUCCESS] Code coverage policy passed with 59.8963% (693 branches).
Finishing: Check build quality
```

Current config
```
 - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
    displayName: 'Check build quality'
    inputs:
      checkWarnings: false
      warningFailOption: fixed
      warningFilters: ''
      showStatistics: true
      checkCoverage: true
      coverageFailOption: build
      coverageType: branches
      baseDefinitionId: $(SPK_DEFINITION_ID)
      baseBranchRef: refs/heads/master
      runTitle: 'Code Coverage Evaluation'
    condition: and(eq(variables['Agent.JobStatus'], 'Succeeded'), endsWith(variables['Agent.JobName'], 'node_12_x'))
```
