### ISSUE TITLE
Warnings not detected in current build

### ISSUE THREAD

**Issue by mjvk** [MicrosoftPremier/VstsExtensions#69]
Running build quality checks with warning task filters seem to match for builds that have been done (baseline) but not for the current build. How is this possible? It depends on other jobs, i.e.:

``` 
dependsOn:
      - BuildAndTestMasterCoverage
      - StaticAnalysisMaster
```

Log:
```
Starting: Check build quality against previous commit
==============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 6.3.0
Author       : Microsoft Premier Services
Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Using IdentifierJobResolver
Validating build warnings policy...
[WARNING] The specified task filters did not match any build task.
##[warning]The specified task filters did not match any build task.
Total warnings: 0
Filtered warnings: 0
Found baseline build with ID 9870.
Counting warnings from tasks:
- Run linters
-   Total warnings: 0, Filtered warnings: 0
- Run linters
-   Total warnings: 114, Filtered warnings: 114
Total warnings: 114
Filtered warnings: 114
[SUCCESS] Warnings policy passed with 0 warning(s).
Validating code coverage policy...
Waiting for code coverage data...
Waiting for code coverage data...
Waiting for code coverage data...
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total branches: 992
Covered branches: 454
Code Coverage (%): 45.7661
Found baseline build with ID 9870.
Successfully read code coverage data from build.
Evaluating coverage data from 1 filtered code coverage data sets...
Total branches: 992
Covered branches: 454
Code Coverage (%): 45.7661
[SUCCESS] Code coverage policy passed with 45.7661% (454/992 branches).
Finishing: Check build quality against previous commit
```
yaml:
```
- job: CheckQualityMaster
        displayName: Check MASTER quality
        steps:
          - checkout: none
          - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
            displayName: "Check build quality against previous commit"
            condition: not(eq(variables['Build.Reason'], 'PullRequest'))
            inputs:
              checkWarnings: true
              warningFailOption: build
              warningTaskFilters: /.*lint.*/i
              checkCoverage: true
              coverageFailOption: build
              coverageType: branches
              coverageDeltaType: absolute
              forceCoverageImprovement: false
              allowCoverageVariance: false
              explicitFilter: true
              useUncoveredElements: true
```
