### ISSUE TITLE
Getting Warning about task filter when using default value

### ISSUE THREAD

**Issue by NorthHighlandNicole** [MicrosoftPremier/VstsExtensions#75]
Why am I getting warning "The specified task filters did not match any build task." even though I am using the default value?

It seems it doesn't matter if I leave warningTaskFilters parameter off altogether if I use
`warningTaskFilters: '/^((vs|ms)build|ant(\\s+.+)?|gradle(w)?(\\s+.+)?|grunt|gulp|maven(\\s+.+)?|xamarin(android|ios)|xcode(\\s+.+)?|cmake|build\\s+.+)$/i'`

This only seems to have started happening after I moved the build job, that contains the step to build & the quality check step to a template.

This is my task yaml
```
- task: BuildQualityChecks@6
      displayName: Check for Build Warnings
      inputs:
        checkWarnings: true
        warningFailOption: 'fixed'
        warningFilters: ''
        warningTaskFilters: '/^((vs|ms)build|ant(\\s+.+)?|gradle(w)?(\s+.+)?|grunt|gulp|maven(\s+.+)?|xamarin(android|ios)|xcode(\s+.+)?|cmake|build\s+.+)$/i'
        warningThreshold: '0'
        showStatistics: true
```
