### ISSUE TITLE
[BQC] Status passed when build times out

### ISSUE THREAD

**Issue by mjvk** [MicrosoftPremier/VstsExtensions#80]
When getting the coverage data times out (##[warning]Unable to get code coverage data within the maximum wait time.) the policy status is marked as OK. In my case the build is marked as failed so the PR is not able to complete but it still seems a bit weird?

The status reported is Code coverage policy passed with 0% (0/0 branches).

**Comment by ReneSchumacher** [comment]
Can you send me the full configuration of the task so I can check what's going on? The timeout is just a warning and the policy assumes zero coverage as a result. In most cases this should fail the policy but this actually depends on the compare value.

Policy result and PR status should always go together but I might have missed something.

**Comment by mjvk** [comment]
Maybe it is due to the uncovered branches part, having zero uncovered branches is of course very nice

```
          - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
            displayName: "Check build quality against previous commit"
            condition: not(eq(variables['Build.Reason'], 'PullRequest'))
            continueOnError: true
            inputs:
              runTitle: "MasterUnitTestCoveragePrevious"
              checkCoverage: true
              coverageFailOption: build
              coverageType: branches
              coverageDeltaType: absolute
              forceCoverageImprovement: false
              explicitFilter: true
              useUncoveredElements: true
          - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
            displayName: "Check build quality against target branch"
            condition: eq(variables['Build.Reason'], 'PullRequest')
            continueOnError: true
            inputs:
              runTitle: "MasterUnitTestCoveragePullRequest"
              baseBranchRef: $(System.PullRequest.TargetBranch)
              checkCoverage: true
              coverageFailOption: build
              coverageType: branches
              coverageDeltaType: absolute
              forceCoverageImprovement: false
              explicitFilter: true
              useUncoveredElements: true
```
