### ISSUE TITLE
Access issue for CreateWorkItem builds from fork

### ISSUE THREAD

**Issue by seylas** [MicrosoftPremier/VstsExtensions#95]
I'm trying to create a new work item for a failed build from the fork and it fails with the error below:

`##[error]TF400813: The user '' is not authorized to access this resource.`

The same build with the same configuration and PAT token was working fine several weeks ago. Please find task configuration below:

```
  - task: CreateWorkItem@1
    displayName: 'Create Task If Build Fails'
    condition: failed()
    inputs:
      teamProject: 'XXXXXXXXXXX'
      workItemType: 'Task'
      title: 'Platform Build Failure New Stack'
      assignedTo: 'XXXXXX YYYYYYY <xxxxxxx.yyyyyyy@zzzzz.com>'
      areaPath: 'XXXXXXXXXXX\DevOps'
      iterationPath: 'XXXXXXXXXXX'
      fieldMappings: |
        Description=This item was automatically created by Azure Pipeline. Failed build is linked to this task.
      associate: true
      linkWorkItems: true
      linkType: 'System.LinkTypes.Hierarchy-Reverse'
      linkTarget: 'id'
      targetId: '142432'
      authToken: 'test_token.txt'
```
No changes in project configuration were executed, I am able to reproduce this issue by specifying an `authToken` parameter. From my side, it looks like some security rules were updated from extension or Azure DevOps side, and an extension cannot assume user token.
Could you please help me in investigation and check from the extension side if everything works fine?
