### ISSUE TITLE
BQC - Waits indefinitely with the recurring message "Waiting for code coverage data..."

### ISSUE THREAD

**Issue by sdg002** [MicrosoftPremier/VstsExtensions#96]
## Snapshot of from the log

{"id":"5083","url":"https://dev.azure.com/CorResilience/_apis/build/Builds/5083"},"deltaBuild":null}
2020-05-27T17:40:31.8975676Z ##[debug]------------------ END RAW DATA ------------------
2020-05-27T17:40:31.8975885Z Waiting for code coverage data...
2020-05-27T17:40:34.2431324Z ##[debug]-------------------- RAW DATA --------------------
2020-05-27T17:40:34.2432371Z ##[debug]buildCoverageSummary:
2020-05-27T17:40:34.2433094Z ##[debug]{"coverageData":[],"build":{"id":"5083","url":"https://dev.azure.com/CorResilience/_apis/build/Builds/5083"},"deltaBuild":null}
2020-05-27T17:40:34.2434308Z ##[debug]------------------ END RAW DATA ------------------
2020-05-27T17:40:34.2434726Z Waiting for code coverage data...
2020-05-27T17:40:36.5810992Z ##[debug]-------------------- RAW DATA --------------------
2020-05-27T17:40:36.5811648Z ##[debug]buildCoverageSummary:
2020-05-27T17:40:36.5812057Z ##[debug]{"coverageData":[],"build":{"id":"5083","url":"https://dev.azure.com/CorResilience/_apis/build/Builds/5083"},"deltaBuild":null}
2020-05-27T17:40:36.5812506Z ##[debug]------------------ END RAW DATA ------------------
2020-05-27T17:40:36.5812712Z Waiting for code coverage data...
2020-05-27T17:40:37.4370691Z ##[error]The task has timed out.
2020-05-27T17:40:37.4373265Z ##[section]Finishing: Check build quality

## YAML Task 
```
steps:
- task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
  displayName: 'Check build quality'
  inputs:
    checkCoverage: true
    coverageFailOption: fixed
    coverageType: lines
    coverageThreshold: 80
  timeoutInMinutes: 3

```

**Comment by ReneSchumacher** [comment]
Hi @sdg002,

did you publish code coverage data in your pipeline? How are you creating the coverage data? Are you using the Visual Studio Test task or another task?

René

**Comment by sdg002** [comment]
Hi @ReneSchumacher 
Thanks for the quick response. 
We are using MSTEST. Here is a snapshot from our YML.

```
    - script: |        
        dotnet test --logger "trx;LogFileName=Test-Results.trx" "$(System.DefaultWorkingDirectory)/CorResilience.Ingestion.Garmin.Api.Tests" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/coverage1.cobertura.xml
      displayName: Run Unit Tests

- task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/Test-*.trx'
        searchFolder: '$(System.DefaultWorkingDirectory)/'
        
    - task: reportgenerator@4
      displayName: ReportGenerator
      inputs:
        reports: '$(Build.SourcesDirectory)/TestResults/Coverage/*.xml'
        targetdir: '$(Build.SourcesDirectory)/TestResults/Coverage'
        sourcedirs: '$(Build.SourcesDirectory)'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage results'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Build.SourcesDirectory)/TestResults/Coverage/*cobertura.xml'
        reportDirectory: '$(Build.SourcesDirectory)/TestResults/Coverage'        

    - task: BuildQualityChecks@6
      inputs:
        checkCoverage: true
        coverageFailOption: 'fixed'
        coverageType: 'lines'
        coverageThreshold: '80'

    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        arguments: '--configuration Release /p:Version=$(MajorVersion).$(MinorVersion).$(PatchNumber) /p:FileVersion=$(Build.BuildNumber) --output publish_output'
        projects: "$(System.DefaultWorkingDirectory)/CorResilience.Ingestion.Garmin.Api/*.csproj"
        publishWebProjects: false
        modifyOutputPath: true
        zipAfterPublish: false
      displayName: Publish Function App

```
